version: '3.8'

services:
  postgres:
    container_name: rustmxchat-pg
    image: postgres:12-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: rustmxchat
      POSTGRES_PASSWORD: rustmxchat
      POSTGRES_DB: rustmxchat
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
