//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::chat::Entity as Chat;
pub use super::message::Entity as Message;
pub use super::user::Entity as User;
pub use super::user_in_chat::Entity as UserInChat;
